name: pattern_detection
plot_title: Pattern Detection
running_time: 35
repeats: 1

settings:
  all:
    symbol_bits: 2
  client:
    rate: 1000
  server:
    reporter_name: influx
    report_received: true

override_settings:
  - all:
      symbol_bits: 2
  - all:
      symbol_bits: 3
  - all:
      symbol_bits: 4
  - all:
      symbol_bits: 8
