name: reordering_detector
plot_title: Actual vs. Estimated Reordering
running_time: 100
repeats: 1

settings:
  all:
    symbol_bits: 2
  client: {}
  server:
    reporter_name: http
    reporter_args: 65536
